version: "2.4"

services:
  fastapi-with-db:
      image: signoz/sample-fastapi-with-db
      ports:
      - "5000:5000"
      environment:
      - REDIS_HOST=redisi
      - MONGO_HOST=mongo
      - OTEL_METRICS_EXPORTER=none
      - OTEL_RESOURCE_ATTRIBUTES=service.name=fastAPI3
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://stagingapp.signoz.io:4317

  mongo:
    image: mongo:latest
    ports:
    - 27017
  redis:
    image: redis:latest
    ports:
    - 6379
    