version: "2.4"

services:

  fastapi-service:
      build:
        context: .
      image: sample-fastapi-app
      ports:
      - "5000:5000"
      environment:
      - DB_HOST=mongo
  mongo:
    image: mongo:latest
    